# Generated by Django 3.0.2 on 2020-02-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('author', models.CharField(max_length=45)),
                ('ding', models.CharField(max_length=45)),
                ('content', models.CharField(max_length=225)),
                ('img_url', models.URLField(max_length=225)),
            ],
        ),
    ]
